/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:7a3cb83e-e7ff-48f6-a894-d8ba4c43df3c",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_WGABllNHn",
  "aws_user_pools_web_client_id": "48k74ljkfse4l3d0vts3chhqah",
  "oauth": {},
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "PHONE_NUMBER"
  ]
};


export default awsmobile;
